development:
  password: 8907b5199950d470ad1e2d36d298932a
 # theme_id: "41394634801" #home page i am working on
 # theme_id: "44427477041" #Copy of BrocElite - New Home Page
 # theme_id: "77132955697" #BrocElite - New Home Page v2
  theme_id: "78566260785" #New HomePage + Checkout
  store: brocelite.myshopify.com
